package mapeo;
// Generated 22/08/2014 02:20:23 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * DependenciaDestino generated by hbm2java
 */
public class DependenciaDestino  implements java.io.Serializable {


     private BigDecimal depDestCod;
     private String depDestNombre;

    public DependenciaDestino() {
    }

	
    public DependenciaDestino(BigDecimal depDestCod) {
        this.depDestCod = depDestCod;
    }
    public DependenciaDestino(BigDecimal depDestCod, String depDestNombre) {
       this.depDestCod = depDestCod;
       this.depDestNombre = depDestNombre;
    }
   
    public BigDecimal getDepDestCod() {
        return this.depDestCod;
    }
    
    public void setDepDestCod(BigDecimal depDestCod) {
        this.depDestCod = depDestCod;
    }
    public String getDepDestNombre() {
        return this.depDestNombre;
    }
    
    public void setDepDestNombre(String depDestNombre) {
        this.depDestNombre = depDestNombre;
    }




}


