package mapeo;
// Generated 22/08/2014 02:20:23 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * DepeorigTrammovId generated by hbm2java
 */
public class DepeorigTrammovId  implements java.io.Serializable {


     private BigDecimal depOrigCod;
     private BigDecimal idMovi;

    public DepeorigTrammovId() {
    }

    public DepeorigTrammovId(BigDecimal depOrigCod, BigDecimal idMovi) {
       this.depOrigCod = depOrigCod;
       this.idMovi = idMovi;
    }
   
    public BigDecimal getDepOrigCod() {
        return this.depOrigCod;
    }
    
    public void setDepOrigCod(BigDecimal depOrigCod) {
        this.depOrigCod = depOrigCod;
    }
    public BigDecimal getIdMovi() {
        return this.idMovi;
    }
    
    public void setIdMovi(BigDecimal idMovi) {
        this.idMovi = idMovi;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DepeorigTrammovId) ) return false;
		 DepeorigTrammovId castOther = ( DepeorigTrammovId ) other; 
         
		 return ( (this.getDepOrigCod()==castOther.getDepOrigCod()) || ( this.getDepOrigCod()!=null && castOther.getDepOrigCod()!=null && this.getDepOrigCod().equals(castOther.getDepOrigCod()) ) )
 && ( (this.getIdMovi()==castOther.getIdMovi()) || ( this.getIdMovi()!=null && castOther.getIdMovi()!=null && this.getIdMovi().equals(castOther.getIdMovi()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDepOrigCod() == null ? 0 : this.getDepOrigCod().hashCode() );
         result = 37 * result + ( getIdMovi() == null ? 0 : this.getIdMovi().hashCode() );
         return result;
   }   


}


