package mapeo;
// Generated 22/08/2014 02:20:23 PM by Hibernate Tools 3.6.0



/**
 * DepeorigTrammov generated by hbm2java
 */
public class DepeorigTrammov  implements java.io.Serializable {


     private DepeorigTrammovId id;
     private TramiteMovimiento tramiteMovimiento;
     private DependenciaOrigen dependenciaOrigen;

    public DepeorigTrammov() {
    }

	
    public DepeorigTrammov(DepeorigTrammovId id) {
        this.id = id;
    }
    public DepeorigTrammov(DepeorigTrammovId id, TramiteMovimiento tramiteMovimiento, DependenciaOrigen dependenciaOrigen) {
       this.id = id;
       this.tramiteMovimiento = tramiteMovimiento;
       this.dependenciaOrigen = dependenciaOrigen;
    }
   
    public DepeorigTrammovId getId() {
        return this.id;
    }
    
    public void setId(DepeorigTrammovId id) {
        this.id = id;
    }
    public TramiteMovimiento getTramiteMovimiento() {
        return this.tramiteMovimiento;
    }
    
    public void setTramiteMovimiento(TramiteMovimiento tramiteMovimiento) {
        this.tramiteMovimiento = tramiteMovimiento;
    }
    public DependenciaOrigen getDependenciaOrigen() {
        return this.dependenciaOrigen;
    }
    
    public void setDependenciaOrigen(DependenciaOrigen dependenciaOrigen) {
        this.dependenciaOrigen = dependenciaOrigen;
    }




}


