package mapeo;
// Generated 22/08/2014 02:20:23 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DependenciaOrigen generated by hbm2java
 */
public class DependenciaOrigen  implements java.io.Serializable {


     private BigDecimal depOrigCod;
     private String depOrigNombre;
     private Set<TramiteDatos> tramiteDatoses = new HashSet<TramiteDatos>(0);
     private Set<DepeorigTrammov> depeorigTrammovs = new HashSet<DepeorigTrammov>(0);

    public DependenciaOrigen() {
    }

	
    public DependenciaOrigen(BigDecimal depOrigCod, String depOrigNombre) {
        this.depOrigCod = depOrigCod;
        this.depOrigNombre = depOrigNombre;
    }
    public DependenciaOrigen(BigDecimal depOrigCod, String depOrigNombre, Set<TramiteDatos> tramiteDatoses, Set<DepeorigTrammov> depeorigTrammovs) {
       this.depOrigCod = depOrigCod;
       this.depOrigNombre = depOrigNombre;
       this.tramiteDatoses = tramiteDatoses;
       this.depeorigTrammovs = depeorigTrammovs;
    }
   
    public BigDecimal getDepOrigCod() {
        return this.depOrigCod;
    }
    
    public void setDepOrigCod(BigDecimal depOrigCod) {
        this.depOrigCod = depOrigCod;
    }
    public String getDepOrigNombre() {
        return this.depOrigNombre;
    }
    
    public void setDepOrigNombre(String depOrigNombre) {
        this.depOrigNombre = depOrigNombre;
    }
    public Set<TramiteDatos> getTramiteDatoses() {
        return this.tramiteDatoses;
    }
    
    public void setTramiteDatoses(Set<TramiteDatos> tramiteDatoses) {
        this.tramiteDatoses = tramiteDatoses;
    }
    public Set<DepeorigTrammov> getDepeorigTrammovs() {
        return this.depeorigTrammovs;
    }
    
    public void setDepeorigTrammovs(Set<DepeorigTrammov> depeorigTrammovs) {
        this.depeorigTrammovs = depeorigTrammovs;
    }




}


