package mapeo;
// Generated 22/08/2014 02:20:23 PM by Hibernate Tools 3.6.0



/**
 * IndicadTrammov generated by hbm2java
 */
public class IndicadTrammov  implements java.io.Serializable {


     private IndicadTrammovId id;
     private TramiteMovimiento tramiteMovimiento;
     private Indicador indicador;

    public IndicadTrammov() {
    }

	
    public IndicadTrammov(IndicadTrammovId id) {
        this.id = id;
    }
    public IndicadTrammov(IndicadTrammovId id, TramiteMovimiento tramiteMovimiento, Indicador indicador) {
       this.id = id;
       this.tramiteMovimiento = tramiteMovimiento;
       this.indicador = indicador;
    }
   
    public IndicadTrammovId getId() {
        return this.id;
    }
    
    public void setId(IndicadTrammovId id) {
        this.id = id;
    }
    public TramiteMovimiento getTramiteMovimiento() {
        return this.tramiteMovimiento;
    }
    
    public void setTramiteMovimiento(TramiteMovimiento tramiteMovimiento) {
        this.tramiteMovimiento = tramiteMovimiento;
    }
    public Indicador getIndicador() {
        return this.indicador;
    }
    
    public void setIndicador(Indicador indicador) {
        this.indicador = indicador;
    }




}


