package mapeo;
// Generated 22/08/2014 02:20:23 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * IndicadTrammovId generated by hbm2java
 */
public class IndicadTrammovId  implements java.io.Serializable {


     private BigDecimal idMovi;
     private BigDecimal indcadCod;

    public IndicadTrammovId() {
    }

    public IndicadTrammovId(BigDecimal idMovi, BigDecimal indcadCod) {
       this.idMovi = idMovi;
       this.indcadCod = indcadCod;
    }
   
    public BigDecimal getIdMovi() {
        return this.idMovi;
    }
    
    public void setIdMovi(BigDecimal idMovi) {
        this.idMovi = idMovi;
    }
    public BigDecimal getIndcadCod() {
        return this.indcadCod;
    }
    
    public void setIndcadCod(BigDecimal indcadCod) {
        this.indcadCod = indcadCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IndicadTrammovId) ) return false;
		 IndicadTrammovId castOther = ( IndicadTrammovId ) other; 
         
		 return ( (this.getIdMovi()==castOther.getIdMovi()) || ( this.getIdMovi()!=null && castOther.getIdMovi()!=null && this.getIdMovi().equals(castOther.getIdMovi()) ) )
 && ( (this.getIndcadCod()==castOther.getIndcadCod()) || ( this.getIndcadCod()!=null && castOther.getIndcadCod()!=null && this.getIndcadCod().equals(castOther.getIndcadCod()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdMovi() == null ? 0 : this.getIdMovi().hashCode() );
         result = 37 * result + ( getIndcadCod() == null ? 0 : this.getIndcadCod().hashCode() );
         return result;
   }   


}


