package mapeo;
// Generated 22/08/2014 02:20:23 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Indicador generated by hbm2java
 */
public class Indicador  implements java.io.Serializable {


     private BigDecimal indcadCod;
     private String indicNombre;
     private Set<IndicadTrammov> indicadTrammovs = new HashSet<IndicadTrammov>(0);

    public Indicador() {
    }

	
    public Indicador(BigDecimal indcadCod) {
        this.indcadCod = indcadCod;
    }
    public Indicador(BigDecimal indcadCod, String indicNombre, Set<IndicadTrammov> indicadTrammovs) {
       this.indcadCod = indcadCod;
       this.indicNombre = indicNombre;
       this.indicadTrammovs = indicadTrammovs;
    }
   
    public BigDecimal getIndcadCod() {
        return this.indcadCod;
    }
    
    public void setIndcadCod(BigDecimal indcadCod) {
        this.indcadCod = indcadCod;
    }
    public String getIndicNombre() {
        return this.indicNombre;
    }
    
    public void setIndicNombre(String indicNombre) {
        this.indicNombre = indicNombre;
    }
    public Set<IndicadTrammov> getIndicadTrammovs() {
        return this.indicadTrammovs;
    }
    
    public void setIndicadTrammovs(Set<IndicadTrammov> indicadTrammovs) {
        this.indicadTrammovs = indicadTrammovs;
    }




}


