package mapeo;
// Generated 22/08/2014 02:20:23 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Oficina generated by hbm2java
 */
public class Oficina  implements java.io.Serializable {


     private String idOficina;
     private String nombreOficina;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Oficina() {
    }

	
    public Oficina(String idOficina) {
        this.idOficina = idOficina;
    }
    public Oficina(String idOficina, String nombreOficina, Set<Usuario> usuarios) {
       this.idOficina = idOficina;
       this.nombreOficina = nombreOficina;
       this.usuarios = usuarios;
    }
   
    public String getIdOficina() {
        return this.idOficina;
    }
    
    public void setIdOficina(String idOficina) {
        this.idOficina = idOficina;
    }
    public String getNombreOficina() {
        return this.nombreOficina;
    }
    
    public void setNombreOficina(String nombreOficina) {
        this.nombreOficina = nombreOficina;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


