package mapeo;
// Generated 22/08/2014 02:20:23 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * TramiteDatos generated by hbm2java
 */
public class TramiteDatos  implements java.io.Serializable {


     private BigDecimal idTramite;
     private Usuario usuario;
     private DependenciaOrigen dependenciaOrigen;
     private String tramNum;
     private Date tramFecha;
     private String tramObs;
     private String estaDescrip;
     private String docuPric;
     private String docuNombre;
     private String docuNum;
     private String docuSiglas;
     private String docuAnio;

    public TramiteDatos() {
    }

	
    public TramiteDatos(BigDecimal idTramite, Usuario usuario, DependenciaOrigen dependenciaOrigen, String tramNum, Date tramFecha, String docuPric, String docuNombre) {
        this.idTramite = idTramite;
        this.usuario = usuario;
        this.dependenciaOrigen = dependenciaOrigen;
        this.tramNum = tramNum;
        this.tramFecha = tramFecha;
        this.docuPric = docuPric;
        this.docuNombre = docuNombre;
    }
    public TramiteDatos(BigDecimal idTramite, Usuario usuario, DependenciaOrigen dependenciaOrigen, String tramNum, Date tramFecha, String tramObs, String estaDescrip, String docuPric, String docuNombre, String docuNum, String docuSiglas, String docuAnio) {
       this.idTramite = idTramite;
       this.usuario = usuario;
       this.dependenciaOrigen = dependenciaOrigen;
       this.tramNum = tramNum;
       this.tramFecha = tramFecha;
       this.tramObs = tramObs;
       this.estaDescrip = estaDescrip;
       this.docuPric = docuPric;
       this.docuNombre = docuNombre;
       this.docuNum = docuNum;
       this.docuSiglas = docuSiglas;
       this.docuAnio = docuAnio;
    }
   
    public BigDecimal getIdTramite() {
        return this.idTramite;
    }
    
    public void setIdTramite(BigDecimal idTramite) {
        this.idTramite = idTramite;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public DependenciaOrigen getDependenciaOrigen() {
        return this.dependenciaOrigen;
    }
    
    public void setDependenciaOrigen(DependenciaOrigen dependenciaOrigen) {
        this.dependenciaOrigen = dependenciaOrigen;
    }
    public String getTramNum() {
        return this.tramNum;
    }
    
    public void setTramNum(String tramNum) {
        this.tramNum = tramNum;
    }
    public Date getTramFecha() {
        return this.tramFecha;
    }
    
    public void setTramFecha(Date tramFecha) {
        this.tramFecha = tramFecha;
    }
    public String getTramObs() {
        return this.tramObs;
    }
    
    public void setTramObs(String tramObs) {
        this.tramObs = tramObs;
    }
    public String getEstaDescrip() {
        return this.estaDescrip;
    }
    
    public void setEstaDescrip(String estaDescrip) {
        this.estaDescrip = estaDescrip;
    }
    public String getDocuPric() {
        return this.docuPric;
    }
    
    public void setDocuPric(String docuPric) {
        this.docuPric = docuPric;
    }
    public String getDocuNombre() {
        return this.docuNombre;
    }
    
    public void setDocuNombre(String docuNombre) {
        this.docuNombre = docuNombre;
    }
    public String getDocuNum() {
        return this.docuNum;
    }
    
    public void setDocuNum(String docuNum) {
        this.docuNum = docuNum;
    }
    public String getDocuSiglas() {
        return this.docuSiglas;
    }
    
    public void setDocuSiglas(String docuSiglas) {
        this.docuSiglas = docuSiglas;
    }
    public String getDocuAnio() {
        return this.docuAnio;
    }
    
    public void setDocuAnio(String docuAnio) {
        this.docuAnio = docuAnio;
    }




}


