package mapeo;
// Generated 22/08/2014 02:20:23 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TramiteMovimiento generated by hbm2java
 */
public class TramiteMovimiento  implements java.io.Serializable {


     private BigDecimal idMovi;
     private String tramNum;
     private BigDecimal movimientoNum;
     private Date movimientoFechaEnvio;
     private Date movimientoFechaIng;
     private String movimientoObserv;
     private String movimientoEstado;
     private Set<IndicadTrammov> indicadTrammovs = new HashSet<IndicadTrammov>(0);
     private Set<UsuTrammov> usuTrammovs = new HashSet<UsuTrammov>(0);
     private Set<DepeorigTrammov> depeorigTrammovs = new HashSet<DepeorigTrammov>(0);

    public TramiteMovimiento() {
    }

	
    public TramiteMovimiento(BigDecimal idMovi, String tramNum, BigDecimal movimientoNum, Date movimientoFechaEnvio, Date movimientoFechaIng, String movimientoEstado) {
        this.idMovi = idMovi;
        this.tramNum = tramNum;
        this.movimientoNum = movimientoNum;
        this.movimientoFechaEnvio = movimientoFechaEnvio;
        this.movimientoFechaIng = movimientoFechaIng;
        this.movimientoEstado = movimientoEstado;
    }
    public TramiteMovimiento(BigDecimal idMovi, String tramNum, BigDecimal movimientoNum, Date movimientoFechaEnvio, Date movimientoFechaIng, String movimientoObserv, String movimientoEstado, Set<IndicadTrammov> indicadTrammovs, Set<UsuTrammov> usuTrammovs, Set<DepeorigTrammov> depeorigTrammovs) {
       this.idMovi = idMovi;
       this.tramNum = tramNum;
       this.movimientoNum = movimientoNum;
       this.movimientoFechaEnvio = movimientoFechaEnvio;
       this.movimientoFechaIng = movimientoFechaIng;
       this.movimientoObserv = movimientoObserv;
       this.movimientoEstado = movimientoEstado;
       this.indicadTrammovs = indicadTrammovs;
       this.usuTrammovs = usuTrammovs;
       this.depeorigTrammovs = depeorigTrammovs;
    }
   
    public BigDecimal getIdMovi() {
        return this.idMovi;
    }
    
    public void setIdMovi(BigDecimal idMovi) {
        this.idMovi = idMovi;
    }
    public String getTramNum() {
        return this.tramNum;
    }
    
    public void setTramNum(String tramNum) {
        this.tramNum = tramNum;
    }
    public BigDecimal getMovimientoNum() {
        return this.movimientoNum;
    }
    
    public void setMovimientoNum(BigDecimal movimientoNum) {
        this.movimientoNum = movimientoNum;
    }
    public Date getMovimientoFechaEnvio() {
        return this.movimientoFechaEnvio;
    }
    
    public void setMovimientoFechaEnvio(Date movimientoFechaEnvio) {
        this.movimientoFechaEnvio = movimientoFechaEnvio;
    }
    public Date getMovimientoFechaIng() {
        return this.movimientoFechaIng;
    }
    
    public void setMovimientoFechaIng(Date movimientoFechaIng) {
        this.movimientoFechaIng = movimientoFechaIng;
    }
    public String getMovimientoObserv() {
        return this.movimientoObserv;
    }
    
    public void setMovimientoObserv(String movimientoObserv) {
        this.movimientoObserv = movimientoObserv;
    }
    public String getMovimientoEstado() {
        return this.movimientoEstado;
    }
    
    public void setMovimientoEstado(String movimientoEstado) {
        this.movimientoEstado = movimientoEstado;
    }
    public Set<IndicadTrammov> getIndicadTrammovs() {
        return this.indicadTrammovs;
    }
    
    public void setIndicadTrammovs(Set<IndicadTrammov> indicadTrammovs) {
        this.indicadTrammovs = indicadTrammovs;
    }
    public Set<UsuTrammov> getUsuTrammovs() {
        return this.usuTrammovs;
    }
    
    public void setUsuTrammovs(Set<UsuTrammov> usuTrammovs) {
        this.usuTrammovs = usuTrammovs;
    }
    public Set<DepeorigTrammov> getDepeorigTrammovs() {
        return this.depeorigTrammovs;
    }
    
    public void setDepeorigTrammovs(Set<DepeorigTrammov> depeorigTrammovs) {
        this.depeorigTrammovs = depeorigTrammovs;
    }




}


