package mapeo;
// Generated 22/08/2014 02:20:23 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * UsuTrammovId generated by hbm2java
 */
public class UsuTrammovId  implements java.io.Serializable {


     private String usuarioId;
     private BigDecimal idMovi;

    public UsuTrammovId() {
    }

    public UsuTrammovId(String usuarioId, BigDecimal idMovi) {
       this.usuarioId = usuarioId;
       this.idMovi = idMovi;
    }
   
    public String getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(String usuarioId) {
        this.usuarioId = usuarioId;
    }
    public BigDecimal getIdMovi() {
        return this.idMovi;
    }
    
    public void setIdMovi(BigDecimal idMovi) {
        this.idMovi = idMovi;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuTrammovId) ) return false;
		 UsuTrammovId castOther = ( UsuTrammovId ) other; 
         
		 return ( (this.getUsuarioId()==castOther.getUsuarioId()) || ( this.getUsuarioId()!=null && castOther.getUsuarioId()!=null && this.getUsuarioId().equals(castOther.getUsuarioId()) ) )
 && ( (this.getIdMovi()==castOther.getIdMovi()) || ( this.getIdMovi()!=null && castOther.getIdMovi()!=null && this.getIdMovi().equals(castOther.getIdMovi()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsuarioId() == null ? 0 : this.getUsuarioId().hashCode() );
         result = 37 * result + ( getIdMovi() == null ? 0 : this.getIdMovi().hashCode() );
         return result;
   }   


}


